library(SeuratObject)
library(Seurat)
library(Signac)
library(harmony)
library(ggplot2)
library(EnsDb.Hsapiens.v86)
library(AnnotationFilter)
#library(SeuratDisk)
library(dplyr)
library(qlcMatrix)
library(BSgenome.Hsapiens.UCSC.hg38)
library(data.table)
library(future)
library(MASS)
library(cluster)
library(igraph)
library(reshape2)
library(mclust)
#library(knitr)
source(file.path(Rmultiome_path, "functions", "premerge_processing_functions.R"))
source(file.path(Rmultiome_path, "functions", "postmerge_processing_functions.R"))
source(file.path(Rmultiome_path, "functions", "postmerge_parameter_functions.R"))
source(file.path(Rmultiome_path, "functions", "premerge_parameter_functions.R"))
source(file.path(Rmultiome_path, "functions", "helper_functions.R"))
source(file.path(Rmultiome_path, "functions", "DE_functions.R"))
source(file.path(Rmultiome_path, "functions", "qc_functions.R"))
source(file.path(Rmultiome_path, "functions", "merged_qc_functions.R"))

# multicore for things which might use it
options(future.globals.maxSize = 48000 * 1024^2) 
