suppressPackageStartupMessages(library(SeuratObject))
suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(Signac))
suppressPackageStartupMessages(library(harmony))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(EnsDb.Hsapiens.v86))
suppressPackageStartupMessages(library(AnnotationFilter))
#library(SeuratDisk)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(qlcMatrix))
suppressPackageStartupMessages(library(BSgenome.Hsapiens.UCSC.hg38))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(future))
suppressPackageStartupMessages(library(future.apply))
suppressPackageStartupMessages(library(MASS))
suppressPackageStartupMessages(library(cluster))
suppressPackageStartupMessages(library(igraph))
suppressPackageStartupMessages(library(reshape2))
suppressPackageStartupMessages(library(mclust))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(scDblFinder))
suppressPackageStartupMessages(library(SingleCellExperiment))
#library(knitr)
source(file.path(Rmultiome_path, "functions", "premerge_processing_functions.R"))
source(file.path(Rmultiome_path, "functions", "postmerge_processing_functions.R"))
source(file.path(Rmultiome_path, "functions", "postmerge_parameter_functions.R"))
source(file.path(Rmultiome_path, "functions", "premerge_parameter_functions.R"))
source(file.path(Rmultiome_path, "functions", "helper_functions.R"))
source(file.path(Rmultiome_path, "functions", "DEDA_functions.R"))
source(file.path(Rmultiome_path, "functions", "qc_functions.R"))
source(file.path(Rmultiome_path, "functions", "merged_qc_functions.R"))
source(file.path(Rmultiome_path, "functions", "celltyping_functions.R"))
source(file.path(Rmultiome_path, "config", "Zillich_Nature_markers.R"))

# multicore for things which might use it
options(future.globals.maxSize = 48000 * 1024^2) 
